##### Terminal #####
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'

##### Input #####
set -s escape-time 10
set -g mouse on
set -g focus-events on

# OSC52 support
set -s set-clipboard on
set -g allow-passthrough on

# vi copy mode
set -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line

# 统一用 OSC52：把内容写入 tmux buffer 并“写到剪贴板通道”
bind-key -T copy-mode-vi y  send -X copy-pipe "tmux load-buffer -w -; tmux send -X clear-selection"
bind-key -T copy-mode-vi Y  send -X copy-pipe-and-cancel "tmux load-buffer -w -"
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe "tmux load-buffer -w -; tmux send -X clear-selection"

##### Environment #####
set -ga update-environment "SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

##### History #####
set -g history-limit 100000

