model = "glm-5.1"
model_provider = "dashscope"
model_catalog_json = "~/.codex/dashscope-completion-models.json"
model_reasoning_effort = "none"

[tui]
status_line = ["model-with-reasoning", "current-dir", "context-used", "context-window-size", "run-state"]
status_line_use_colors = true

[model_providers.dashscope]
name = "DashScope"
base_url = "https://internal-support.sec-gateway-higress.aliyuncs.com/nocache-forward/v1"
env_key = "DASHSCOPE_API_KEY"
wire_api = "chat"
requires_openai_auth = false
extra_body = { reasoning_effort = "high" }
request_max_retries = 99
request_max_retry_delay_ms = 10000
model_catalog_json = "~/.codex/dashscope-completion-models.json"
