[marketplaces.openai-bundled]
last_updated = "2026-05-09T17:42:35Z"
source = "/Users/yuguorui/.codex/.tmp/bundled-marketplaces/openai-bundled"
source_type = "local"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-09T17:42:59Z"
source = "/Users/yuguorui/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"
source_type = "local"

[marketplaces.claude-plugins-official]
last_updated = "2026-05-24T14:24:32Z"
last_revision = "3449c10cd1f254c2529a4a7e96a094ef118a00a5"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[mcp_servers.browsermcp]
command = "npx"
args = ["@browsermcp/mcp@latest"]

[mcp_servers.exa]
url = "https://mcp.exa.ai/mcp"

[agents]
max_threads = 1000000

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[tui]
status_line = ["model-with-reasoning", "current-dir", "context-used", "context-window-size"]
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4
